### ISSUE TITLE
Crash on startup due to NoClassDefFoundError: DisplayBehaviour when loading CBC Modern Warfare with Create 6.0.8

### ISSUE THREAD

**Issue by mister-cmd** [Cannoneers-of-Create/CreateBigCannons#980]
When launching the game (Forge 1.20.1, Create 6.0.8, Create: Big Cannons 5.11.4), the mod CBC Modern Warfare (version 0.0.6c) causes a NoClassDefFoundError for com.simibubi.create.content.redstone.displayLink.DisplayBehaviour. This error prevents the mod from initializing, and subsequently breaks Create itself due to a failed mixin injection from CBCMW. The game crashes during mod loading.

Steps to Reproduce:
Install Minecraft 1.20.1 with Forge 47.4.10.
Add the following mods:
Create 6.0.8
CBC Modern Warfare 0.0.6c
Create Big Cannons
Launch the game.
Crash occurs during the construction phase of mod loading.

Expected Behavior:
The game should start without errors, and CBC Modern Warfare should work with Create 6.0.8.

Actual Behavior:
The game crashes with the following critical errors (excerpt from the log):

```
[00:52:47] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: cbcmodernwarfare, class riftyboi.cbcmodernwarfare.forge.CBCModernWarfareForge
java.lang.NoClassDefFoundError: com/simibubi/create/content/redstone/displayLink/DisplayBehaviour
...
Caused by: java.lang.ClassNotFoundException: com.simibubi.create.content.redstone.displayLink.DisplayBehaviour
This leads to a critical mixin injection failure in Create:

[00:52:51] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: create, class com.simibubi.create.Create
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method cbcmodernwarfare$tick$openScreen(...) in cbcmodernwarfare-common.mixins.json:SmokeValueSettingsMixin failed injection check, (0/1) succeeded.
The full crash report is attached.
```

Mods & Versions:
CBC Modern Warfare: 0.0.6c+mc.1.20.1-forge
Create: 6.0.8
Forge: 47.4.10
Minecraft: 1.20.1
Create: Big Cannons 5.11.4

Additional Context:
Other mods that depend on Create (e.g., Create Big Cannons) also fail due to the same underlying cause.

The class DisplayBehaviour was present in earlier versions of Create but may have been moved or renamed. Please check compatibility with Create 6.0.8.

Possible Cause:
The mod cbcmodernwarfare references a class from Create that is no longer available or has a different package path in Create 6.0.8. Updating the dependency or using a reflection fallback could resolve the issue.

Attachments:
Full crash log: [latest.log](https://github.com/user-attachments/files/31849167/latest.log)

**Comment by rbasamoyai** [comment]
MW issue
